version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://user:user@database:3306/lbc_api?unix_socket=/var/run/mysqld/mysqld.sock
  database:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lbc_api
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    

